//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_REVIEW
    {
        public int ReviewID { get; set; }
        public string ReviewDescription { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EditionID { get; set; }
        public int ReviewRating { get; set; }
    
        public virtual BOOK_EDITION BOOK_EDITION { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
