//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_EDITION_IMAGE
    {
        public int EditionImageID { get; set; }
        public string EditionImage { get; set; }
        public int EditionID { get; set; }
    
        public virtual BOOK_EDITION BOOK_EDITION { get; set; }
    }
}
