//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_EDITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK_EDITION()
        {
            this.BOOK_EDITION_IMAGE = new HashSet<BOOK_EDITION_IMAGE>();
            this.BOOK_REVIEW = new HashSet<BOOK_REVIEW>();
            this.CUSTOMER_ORDER_DETAIL = new HashSet<CUSTOMER_ORDER_DETAIL>();
            this.STOCK_RECEIVED_NOTE_DETAIL = new HashSet<STOCK_RECEIVED_NOTE_DETAIL>();
            this.CATEGORies = new HashSet<CATEGORY>();
            this.PROMOTIONs = new HashSet<PROMOTION>();
        }
    
        public int EditionID { get; set; }
        public decimal EditionPrice { get; set; }
        public string EditionDescription { get; set; }
        public string EditionYear { get; set; }
        public int EditionPageCount { get; set; }
        public string EditionName { get; set; }
        public string EditionAuthor { get; set; }
        public Nullable<int> BookCollectionID { get; set; }
    
        public virtual BOOK_COLLECTION BOOK_COLLECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_EDITION_IMAGE> BOOK_EDITION_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_REVIEW> BOOK_REVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER_DETAIL> CUSTOMER_ORDER_DETAIL { get; set; }
        public virtual STOCK_INVENTORY STOCK_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_RECEIVED_NOTE_DETAIL> STOCK_RECEIVED_NOTE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMOTION> PROMOTIONs { get; set; }
    }
}
