//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_ORDER()
        {
            this.CUSTOMER_ORDER_DETAIL = new HashSet<CUSTOMER_ORDER_DETAIL>();
            this.SHIP_CONFIRMATION = new HashSet<SHIP_CONFIRMATION>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal OrderTotalPrice { get; set; }
        public string OrderStatus { get; set; }
        public string OrderShippingMethod { get; set; }
        public string OrderPaymentMethod { get; set; }
        public Nullable<int> StaffID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ShipperID { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER_DETAIL> CUSTOMER_ORDER_DETAIL { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIP_CONFIRMATION> SHIP_CONFIRMATION { get; set; }
    }
}
