//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.BANK_ACCOUNT = new HashSet<BANK_ACCOUNT>();
            this.BOOK_REVIEW = new HashSet<BOOK_REVIEW>();
            this.CUSTOMER_ORDER = new HashSet<CUSTOMER_ORDER>();
            this.CUSTOMER_ORDER1 = new HashSet<CUSTOMER_ORDER>();
            this.CUSTOMER_ORDER2 = new HashSet<CUSTOMER_ORDER>();
            this.SHIP_CONFIRMATION = new HashSet<SHIP_CONFIRMATION>();
            this.WALLETs = new HashSet<WALLET>();
            this.BOOK_EDITION = new HashSet<BOOK_EDITION>();
        }
    
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonStatus { get; set; }
        public string AccountID { get; set; }
        public Nullable<int> TierID { get; set; }
        public int ManagerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_ACCOUNT> BANK_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_REVIEW> BOOK_REVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER> CUSTOMER_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER> CUSTOMER_ORDER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER> CUSTOMER_ORDER2 { get; set; }
        public virtual MANAGER MANAGER { get; set; }
        public virtual TIER TIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIP_CONFIRMATION> SHIP_CONFIRMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WALLET> WALLETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_EDITION> BOOK_EDITION { get; set; }
    }
}
