//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMOTION()
        {
            this.BOOK_EDITION = new HashSet<BOOK_EDITION>();
        }
    
        public int PromotionID { get; set; }
        public string PromotionName { get; set; }
        public decimal PromotionDiscount { get; set; }
        public System.DateTime PromotionStartDate { get; set; }
        public System.DateTime PromotionEndDate { get; set; }
        public bool PromotionIsValid { get; set; }
        public int ManagerID { get; set; }
        public string PromotionDetails { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_EDITION> BOOK_EDITION { get; set; }
    }
}
