//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROMOTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMOTION()
        {
            this.BOOK_EDITION = new HashSet<BOOK_EDITION>();
        }

        [Display(Name = "Mã khuyến mãi")]
        public int PromotionID { get; set; }
        [Display(Name = "Tên khuyến mãi")]
        public string PromotionName { get; set; }
        [Display(Name = "Mức giảm giá")]
        public decimal PromotionDiscount { get; set; }
        [Display(Name = "Ngày bắt đầu")]

        public System.DateTime PromotionStartDate { get; set; }
        [Display(Name = "Ngày kết thúc")]

        public System.DateTime PromotionEndDate { get; set; }
        public int ManagerID { get; set; }
        [Display(Name = "Chi tiết khuyến mãi")]
        public string PromotionDetails { get; set; }

        public virtual MANAGER MANAGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_EDITION> BOOK_EDITION { get; set; }
    }
}
