//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLISHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHER()
        {
            this.STOCK_RECEIVED_NOTE = new HashSet<STOCK_RECEIVED_NOTE>();
        }
    
        public int PublisherID { get; set; }
        public string PublisherName { get; set; }
        public string PublisherDescription { get; set; }
        public string PublisherImage { get; set; }
        public int ManagerID { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_RECEIVED_NOTE> STOCK_RECEIVED_NOTE { get; set; }
    }
}
