//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_CONFIRMATION
    {
        public int ShipConfirmationID { get; set; }
        public System.DateTime ConfirmationDate { get; set; }
        public string ConfirmationImage { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ShipperID { get; set; }
    
        public virtual CUSTOMER_ORDER CUSTOMER_ORDER { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
    }
}
