//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_RECEIVED_NOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_RECEIVED_NOTE()
        {
            this.STOCK_RECEIVED_NOTE_DETAIL = new HashSet<STOCK_RECEIVED_NOTE_DETAIL>();
        }
    
        public int StockReceivedNoteID { get; set; }
        public System.DateTime StockReceivedNoteDate { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_RECEIVED_NOTE_DETAIL> STOCK_RECEIVED_NOTE_DETAIL { get; set; }
    }
}
