//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_edition_total_stock_quantity_price_in_this_and_previous_month
    {
        public int EditionID { get; set; }
        public Nullable<int> TongNhapCuaThang { get; set; }
        public Nullable<int> TongNhapThangTruoc { get; set; }
        public Nullable<decimal> TongTienNhapCuaThang { get; set; }
        public Nullable<decimal> TongTienNhapThangTruoc { get; set; }
    }
}
