//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_edition_buy_count
    {
        public int EditionID { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> BuyCount { get; set; }
    }
}
