//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLET
    {
        public int WalletID { get; set; }
        public int CustomerID { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
