//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ORDER_DETAIL
    {
        public Nullable<decimal> DetailCurrentPrice { get; set; }
        public int DetailQuantity { get; set; }
        public int OrderID { get; set; }
        public int EditionID { get; set; }
    
        public virtual BOOK_EDITION BOOK_EDITION { get; set; }
        public virtual CUSTOMER_ORDER CUSTOMER_ORDER { get; set; }
    }
}
