//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_INVENTORY
    {
        public int InventoryStockInTotal { get; set; }
        public int InventoryStockOutTotal { get; set; }
        public int InventoryAvailableStock { get; set; }
        public int EditionID { get; set; }
    
        public virtual BOOK_EDITION BOOK_EDITION { get; set; }
    }
}
